# Generated by Django 5.1.5 on 2025-01-28 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_producto_precio_carrito_productoencarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(through='api.ProductoEnCarrito', to='api.producto'),
        ),
        migrations.AlterField(
            model_name='productoencarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carrito'),
        ),
    ]
