# Generated by Django 5.1.5 on 2025-01-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_carrito_productos_alter_productoencarrito_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='productoencarrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
